version: '3.5'

services:
  app:
    restart: on-failure:2
    image: 'demo-crud:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - 8080:8080
          
  db:
    image: postgres:13.1-alpine
    container_name: db
    ports:
      - 5424:5432
    volumes:
      - ./sql:/sql  
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres